# Bayesian network

In [11]:
import pandas as pd 

# Reading in data 

df = pd.read_csv('./Ordinal Encoded with Scaling (remember to imbalance check in each model).csv')  

df2 = df.drop(columns=['Your level of satisfaction in Online Education'])

df2.head(5) 

Unnamed: 0    Gender  Home Location  Level of Education  Age(Years)  \
0           0  0.826081       0.722049            0.486024   -0.562497   
1           1  0.826081       0.722049            0.486024   -0.249763   
2           2  0.826081      -1.384947            0.486024   -0.562497   
3           3  0.826081       0.722049            0.486024   -0.562497   
4           4  0.826081      -1.384947            0.486024   -0.562497   

   Number of Subjects  Device type used to attend classes  Economic status  \
0            1.411598                           -0.581565        -0.270233   
1           -0.012407                           -0.581565        -0.270233   
2           -0.724409                           -0.581565        -0.270233   
3           -0.724409                           -0.581565        -0.270233   
4           -0.724409                           -0.581565        -0.270233   

   Family size  Internet facility in your locality  ...  Sleep time (Hours)  \
0    -0.334392                            1.378125  ...           -0.716130   
1    -0.334392                           -2.522158  ...           -1.471761   
2     0.474571                           -1.547087  ...            0.039501   
3    -0.334392                            0.403054  ...           -0.716130   
4    -0.334392                           -0.572016  ...            0.039501   

   Time spent on social media (Hours)  Interested in Gaming?  \
0                           -0.880700              -1.088087   
1                           -0.880700               0.919045   
2                           -0.880700              -1.088087   
3                           -0.342697              -1.088087   
4                           -0.342697               0.919045   

   Have separate room for studying?  Engaged in group studies?  \
0                         -1.196072                  -0.822769   
1                          0.836070                  -0.822769   
2                          0.836070                  -0.822769   
3                         -1.196072                   1.215409   
4                          0.836070                   1.215409   

   Average marks scored before pandemic in traditional classroom  \
0                                           1.244915               
1                                           1.244915               
2                                          -0.165943               
3                                           1.244915               
4                                           0.539486               

   Your interaction in online mode  \
0                        -1.747111   
1                        -1.747111   
2                        -1.747111   
3                        -1.747111   
4                         0.063085   

   Clearing doubts with faculties in online mode  Interested in?  \
0                                      -1.576433        0.128714   
1                                      -1.576433        1.458326   
2                                      -1.576433       -1.200899   
3                                      -0.716636        1.458326   
4                                       0.143161       -1.200899   

   Performance in online  
0              -0.362683  
1              -1.925901  
2              -0.362683  
3              -1.404828  
4              -0.362683  

[5 rows x 23 columns]

In [18]:
# Splitting data in training and testing set 
from sklearn.model_selection import train_test_split 

target = df['Your level of satisfaction in Online Education']  

X_train, X_test, y_train, y_test = train_test_split(df2, target, test_size=0.2, random_state=0)   


### Gaussian NB

In [19]:
# Encoding 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn import preprocessing  

model = GaussianNB()

model.fit(X_train, y_train) 

print(classification_report(y_test, model.predict(X_test)))



              precision    recall  f1-score   support

           0       0.64      0.81      0.72       105
           1       0.53      0.59      0.56        39
           2       0.75      0.38      0.51        63

    accuracy                           0.64       207
   macro avg       0.64      0.59      0.59       207
weighted avg       0.66      0.64      0.62       207



### Confusion Matrix

In [20]:
from sklearn.metrics import multilabel_confusion_matrix 

print(multilabel_confusion_matrix(y_test,model.predict(X_test)))

[[[ 55  47]
  [ 20  85]]

 [[148  20]
  [ 16  23]]

 [[136   8]
  [ 39  24]]]


### K-folds

In [22]:
from sklearn.model_selection import KFold

acc_per_fold = []
loss_per_fold = []
fold_num = 1 


# K-fold Cross Validator
kfold = KFold(n_splits=10, shuffle=True)

for train, test in kfold.split(df2, target):
    # Train on different folds
    #model = create_model()
    hist = model.fit(df2.iloc[train], target[train])
    scores = model.evaluate(df2.iloc[test], target[test], verbose=0)
    print(f'Fold {fold_num} - {model.metrics_names[0]}: {scores[0]}; {model.metrics_names[1]}: {scores[1]*100}%')
    acc_per_fold.append(scores[1] * 100)
    loss_per_fold.append(scores[0])
    # Next fold number
    fold_num = fold_num + 1

AttributeError: 'GaussianNB' object has no attribute 'evaluate'

In [25]:
from sklearn.model_selection import KFold 
from sklearn import cross_validation
import numpy as np 

#Simple K-Fold cross validation. 10 folds.
cv = cross_validation.KFold(len(train), k=10, indices=False)

#iterate through the training and test cross validation segments and
#run the classifier on each one, aggregating the results into a list
results = []
for traincv, testcv in cv:
    probas = model.fit(X_train[traincv], target[traincv]).predict_proba(X_train[testcv])
    results.append(myEvaluationFunc(target[testcv], [x[1] for x in probas]) )

#print out the mean of the cross-validated results
print ("Results: " + str( np.array(results).mean() ))

ImportError: cannot import name 'cross_validation' from 'sklearn' (/Users/andrewnguyen/opt/anaconda3/lib/python3.9/site-packages/sklearn/__init__.py)