In [3]:
import pandas as pd  
import numpy as np

file = pd.read_csv("./Ordinal Encoded with Scaling (remember to imbalance check in each model).csv") 
file.head(5)


Unnamed: 0    Gender  Home Location  Level of Education  Age(Years)  \
0           0  0.826081       0.722049            0.486024   -0.562497   
1           1  0.826081       0.722049            0.486024   -0.249763   
2           2  0.826081      -1.384947            0.486024   -0.562497   
3           3  0.826081       0.722049            0.486024   -0.562497   
4           4  0.826081      -1.384947            0.486024   -0.562497   

   Number of Subjects  Device type used to attend classes  Economic status  \
0            1.411598                           -0.581565        -0.270233   
1           -0.012407                           -0.581565        -0.270233   
2           -0.724409                           -0.581565        -0.270233   
3           -0.724409                           -0.581565        -0.270233   
4           -0.724409                           -0.581565        -0.270233   

   Family size  Internet facility in your locality  ...  \
0    -0.334392                            1.378125  ...   
1    -0.334392                           -2.522158  ...   
2     0.474571                           -1.547087  ...   
3    -0.334392                            0.403054  ...   
4    -0.334392                           -0.572016  ...   

   Time spent on social media (Hours)  Interested in Gaming?  \
0                           -0.880700              -1.088087   
1                           -0.880700               0.919045   
2                           -0.880700              -1.088087   
3                           -0.342697              -1.088087   
4                           -0.342697               0.919045   

   Have separate room for studying?  Engaged in group studies?  \
0                         -1.196072                  -0.822769   
1                          0.836070                  -0.822769   
2                          0.836070                  -0.822769   
3                         -1.196072                   1.215409   
4                          0.836070                   1.215409   

   Average marks scored before pandemic in traditional classroom  \
0                                           1.244915               
1                                           1.244915               
2                                          -0.165943               
3                                           1.244915               
4                                           0.539486               

   Your interaction in online mode  \
0                        -1.747111   
1                        -1.747111   
2                        -1.747111   
3                        -1.747111   
4                         0.063085   

   Clearing doubts with faculties in online mode  Interested in?  \
0                                      -1.576433        0.128714   
1                                      -1.576433        1.458326   
2                                      -1.576433       -1.200899   
3                                      -0.716636        1.458326   
4                                       0.143161       -1.200899   

   Performance in online  Your level of satisfaction in Online Education  
0              -0.362683                                               0  
1              -1.925901                                               1  
2              -0.362683                                               1  
3              -1.404828                                               1  
4              -0.362683                                               0  

[5 rows x 24 columns]

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

train, test = train_test_split(file, test_size = 0.2, random_state=20)

In [11]:
X_train, X_test = train.drop('Your level of satisfaction in Online Education', axis = 1), test.drop('Your level of satisfaction in Online Education', axis = 1)
y_train, y_test = train['Your level of satisfaction in Online Education'], test['Your level of satisfaction in Online Education']

#Create the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

#Train the model and create predictions

reg = model.fit(X_train, y_train)
predictions_test = reg.predict(X_test)

# Printing Predictions
print(predictions_test)

#Calculate performance metrics
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions_test))

#Generate a confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions_test))

[1 0 0 0 0 2 2 1 2 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 1 0 0 0 0 0 0 2 2 2 0 0
 1 0 0 0 0 1 2 2 0 2 0 0 1 0 0 2 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 2 0 0 1 1 2
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 2 0 0 0 0 1 0 0 1 0 2 1
 0 0 2 0 1 1 0 0 0 2 0 0 0 0 0 0 0 2 1 0 2 0 2 1 0 1 0 0 0 0 0 0 0 0 1 1 1
 0 2 0 0 1 0 2 2 1 2 0 2 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 2 0 2 0 0 0 1 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 2 2 0 2 0 0 0]
              precision    recall  f1-score   support

           0       0.61      0.82      0.70       102
           1       0.62      0.42      0.50        50
           2       0.80      0.51      0.62        55

    accuracy                           0.64       207
   macro avg       0.68      0.58      0.61       207
weighted avg       0.66      0.64      0.63       207

[[84 11  7]
 [29 21  0]
 [25  2 28]]


c:\Users\14156\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
