In [4]:
import pandas as pd  
import numpy as np

file = pd.read_csv("./Only Ordinal Encoded.csv") 
file.head(5)


Gender  Home Location  Level of Education  Age(Years)  Number of Subjects  \
0     1.0            1.0                 2.0          18                  11   
1     1.0            1.0                 2.0          19                   7   
2     1.0            0.0                 2.0          18                   5   
3     1.0            1.0                 2.0          18                   5   
4     1.0            0.0                 2.0          18                   5   

   Device type used to attend classes  Economic status  Family size  \
0                                 1.0              0.0            4   
1                                 1.0              0.0            4   
2                                 1.0              0.0            5   
3                                 1.0              0.0            4   
4                                 1.0              0.0            4   

   Internet facility in your locality  Are you involved in any sports?  ...  \
0                                   5                              0.0  ...   
1                                   1                              1.0  ...   
2                                   2                              0.0  ...   
3                                   4                              1.0  ...   
4                                   3                              0.0  ...   

   Time spent on social media (Hours)  Interested in Gaming?  \
0                                   1                    0.0   
1                                   1                    1.0   
2                                   1                    0.0   
3                                   2                    0.0   
4                                   2                    1.0   

   Have separate room for studying?  Engaged in group studies?  \
0                               0.0                        0.0   
1                               1.0                        0.0   
2                               1.0                        0.0   
3                               0.0                        1.0   
4                               1.0                        1.0   

   Average marks scored before pandemic in traditional classroom  \
0                                                9.0               
1                                                9.0               
2                                                7.0               
3                                                9.0               
4                                                8.0               

   Your interaction in online mode  \
0                                1   
1                                1   
2                                1   
3                                1   
4                                3   

   Clearing doubts with faculties in online mode  Interested in?  \
0                                              1             1.0   
1                                              1             2.0   
2                                              1             0.0   
3                                              2             2.0   
4                                              3             0.0   

   Performance in online  Your level of satisfaction in Online Education  
0                      6                                               0  
1                      3                                               1  
2                      6                                               1  
3                      4                                               1  
4                      6                                               0  

[5 rows x 23 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

train, test = train_test_split(file, test_size = 0.2, random_state=20)

In [6]:
X_train, X_test = train.drop('Your level of satisfaction in Online Education', axis = 1), test.drop('Your level of satisfaction in Online Education', axis = 1)
y_train, y_test = train['Your level of satisfaction in Online Education'], test['Your level of satisfaction in Online Education']

#Create the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

#Train the model and create predictions

reg = model.fit(X_train, y_train)
predictions_test = reg.predict(X_test)

# Printing Predictions
print(predictions_test)

#Calculate performance metrics
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions_test))

#Generate a confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions_test))

[1 0 0 0 0 2 2 1 2 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 1 1 0 0 0 0 0 0 2 2 0 0 0
 1 1 0 0 0 1 2 2 0 0 0 0 1 2 0 2 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 2 0 0 0 0 1 0 0 0 0 2 1
 0 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 2 1 0 2 0 2 1 0 1 0 0 0 0 2 0 0 0 1 1 1
 0 2 0 0 1 0 2 2 1 2 0 2 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 2 0 0 0 0 0 1 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 2 0 0 0]
              precision    recall  f1-score   support

           0       0.61      0.85      0.71       102
           1       0.68      0.46      0.55        50
           2       0.81      0.45      0.58        55

    accuracy                           0.65       207
   macro avg       0.70      0.59      0.61       207
weighted avg       0.68      0.65      0.64       207

[[87  9  6]
 [27 23  0]
 [28  2 25]]


c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
